In [1]:
import numpy as np

a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [2]:
print(type(a))

<class 'list'>


In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
print(arr.dtype)

int64


In [6]:
print(arr[0])

1


In [7]:
print(type(arr[0]))

<class 'numpy.int64'>


In [8]:
arr = np.array([100,3.14,True,'Hello'])
print(arr)

['100' '3.14' 'True' 'Hello']


In [9]:
a=[[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [10]:
arr=np.array(a)

In [11]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
print(arr[1,1])

5


In [13]:
a = [[1,2,3],[4,5,6]]
arr = np.array(a, dtype=np.float64)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [17]:
a = [1,2,3,4]
arr = np.array(a, dtype=np.float64)
print(arr)

[1. 2. 3. 4.]


In [18]:
a = [1,2,3,4]
arr = np.array(a, dtype=np.float64)
print(arr)

[1. 2. 3. 4.]


In [19]:
print(arr.ndim)

1


In [20]:
print(arr.shpape)

AttributeError: 'numpy.ndarray' object has no attribute 'shpape'

In [21]:
print(arr.shape)

(4,)
